### ISSUE TITLE
No error messaging

### ISSUE THREAD

**Issue by chrispix** [polpielladev/chatty-cli#1]
I've authenticated with my API key, but no matter what I prompt, I get no response. I assume ChatGPT is returning some kind of error, but nothing is reported in the terminal. Would it be possible to relay errors from ChatGPT?

**Comment by thuss** [comment]
Same issue here, I'm on the free plan, generated an API key, `chatty auth` successful, but `chatty chat` just gives me empty responses to all my queries.

**Comment by polpielladev** [comment]
Thanks for sharing the feedback @chrispix @thuss 🙌

I will look into adding some form of error handling, I am guessing there is an issue with the key, have you copied it directly into the terminal?

**Comment by chrispix** [comment]
> Thanks for sharing the feedback @chrispix @thuss 🙌
> 
> I will look into adding some form of error handling, I am guessing there is an issue with the key, have you copied it directly into the terminal?

Yes. And I checked the `dev.polpiella.chatty` entry in Keychain Access, looks like it was stored correctly (though I was not prompted to unlock keychain first). I was assuming there might be some kind of error message from OpenAI that you could echo to the terminal.

**Comment by chrispix** [comment]
I discovered the issue in my case was that I didn't have pay-as-you-go set up, and my free tokens had expired. Not sure if the API gives you any indication that there are no API tokens available, but if it does, that would be nice.

**Comment by polpielladev** [comment]
Sorry for the late reply but glad to hear that you've found the issue and thank you so much for updating the README ❤️ 

I have created an issue to change SDK providers or roll out my own solution, so I will be looking into that once I have some time: https://github.com/polpielladev/chatty-cli/issues/5

**Comment by polpielladev** [comment]
Closing this as this issue will be fixed as part of #5
