### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by jaroshevskii** [polpielladev/chatty-cli#2]
Add for example MIT License, BSD License, Apache License or any other open source license.

Having a LICENSE file can help establish trust and openness with regard to the project and its authors, which can be important when collaborating with other developers or when publicly distributing the project.

For more information, visit the GitHub Docs:
- [Licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
- [Adding a license to a repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

**Comment by polpielladev** [comment]
Hi @jaroshevskii! Thanks so much for raising the issue, it's something I had in my todo list but never got around to doing.

I have now added an `MIT` license to the repository: https://github.com/polpielladev/chatty-cli/pull/4
